apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: karinenrb/gitopsfc
  newTag: 04e0e72dea7e7b6f8c8c2e87c7d83ad593e4b688
